version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "rootpwd"
       MYSQL_DATABASE: "catalog"
       MYSQL_USER: "catalogapiuser"
       MYSQL_PASSWORD: "catalogapipwd"
       MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - D:\Dev\shop\mysqldata:/var/lib/mysql